import { NextRequest, NextResponse } from 'next/server';

// Import the image generation function from the main route
async function generateImageWithImagen(prompt: string, fastMode: boolean = true): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY not configured');
  }

  // Adjust prompt for fast mode if needed
  const effectivePrompt = fastMode
    ? `${prompt}\n\nGenerate a low-resolution, fast-rendering product image (square 512x512). Keep the design simple, clean background, minimal fine detail.`
    : prompt;

  console.log(`Generating image with Gemini for prompt: ${prompt.substring(0, 100)}...`);

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: effectivePrompt
          }]
        }],
        generationConfig: fastMode ? {
          temperature: 0.4,
          maxOutputTokens: 512,
        } : undefined,
      }),
    }
  );

  if (!response.ok) {
    const errorBody = await response.text();
    console.error('Gemini image generation error response:', errorBody);
    throw new Error(`Gemini image generation error (${response.status}): ${response.statusText}`);
  }

  const data = await response.json();
  console.log('Gemini image generation response received');
  
  // Extract image from response parts
  const parts = data.candidates?.[0]?.content?.parts;
  if (!parts || parts.length === 0) {
    throw new Error('No parts in Gemini response');
  }

  // Find the part with inline_data (the generated image)
  const imagePart = parts.find((part: any) => part.inline_data || part.inlineData);
  if (!imagePart) {
    throw new Error('No image generated by Gemini');
  }

  // Get base64 image data (handle both inline_data and inlineData formats)
  const imageBase64 = imagePart.inline_data?.data || imagePart.inlineData?.data;
  if (!imageBase64) {
    throw new Error('No image data in Gemini response');
  }

  // Use the correct mime type if provided (Gemini may return png or jpeg)
  const mimeType =
    imagePart.inline_data?.mime_type ||
    imagePart.inline_data?.mimeType ||
    imagePart.inlineData?.mime_type ||
    imagePart.inlineData?.mimeType ||
    'image/png';

  // Return as data URL for direct display
  return `data:${mimeType};base64,${imageBase64}`;
}

export async function POST(request: NextRequest) {
  try {
    const { prompt, fastMode = true } = await request.json();

    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      );
    }

    // Generate the image
    const imageUrl = await generateImageWithImagen(prompt, Boolean(fastMode));

    return NextResponse.json({
      success: true,
      dataUrl: imageUrl,
    });

  } catch (error) {
    console.error('Error generating image:', error);
    
    return NextResponse.json(
      { 
        error: 'Failed to generate image',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
