import { NextRequest, NextResponse } from 'next/server';

// Import the image generation function
async function generateImageWithImagen(prompt: string, fastMode: boolean = true): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY not configured');
  }

  // Adjust prompt for fast mode if needed
  const effectivePrompt = fastMode
    ? `${prompt}\n\nGenerate a low-resolution, fast-rendering product image (square 512x512). Keep the design simple, clean background, minimal fine detail.`
    : prompt;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: effectivePrompt
          }]
        }],
        generationConfig: fastMode ? {
          temperature: 0.4,
          maxOutputTokens: 512,
        } : undefined,
      }),
    }
  );

  if (!response.ok) {
    const errorBody = await response.text();
    console.error('Gemini image generation error response:', errorBody);
    throw new Error(`Gemini image generation error (${response.status}): ${response.statusText}`);
  }

  const data = await response.json();
  
  // Extract image from response parts
  const parts = data.candidates?.[0]?.content?.parts;
  if (!parts || parts.length === 0) {
    throw new Error('No parts in Gemini response');
  }

  // Find the part with inline_data (the generated image)
  const imagePart = parts.find((part: any) => part.inline_data || part.inlineData);
  if (!imagePart) {
    throw new Error('No image generated by Gemini');
  }

  // Get base64 image data (handle both inline_data and inlineData formats)
  const imageBase64 = imagePart.inline_data?.data || imagePart.inlineData?.data;
  if (!imageBase64) {
    throw new Error('No image data in Gemini response');
  }

  // Use the correct mime type if provided (Gemini may return png or jpeg)
  const mimeType =
    imagePart.inline_data?.mime_type ||
    imagePart.inline_data?.mimeType ||
    imagePart.inlineData?.mime_type ||
    imagePart.inlineData?.mimeType ||
    'image/png';

  // Return as data URL for direct display
  return `data:${mimeType};base64,${imageBase64}`;
}

async function callGeminiForConcept(originalProduct: any, userPrompt: string, existingConcepts: string[], fastMode: boolean) {
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY not configured');
  }

  const conceptPrompt = `You are a senior industrial designer. Based on the original product and user input, create a new design concept that is different from existing concepts.

ORIGINAL PRODUCT:
- Title: ${originalProduct.title}
- Description: ${originalProduct.description}
- Specifications: ${JSON.stringify(originalProduct.specifications)}

EXISTING CONCEPTS (avoid these themes):
${existingConcepts.map(concept => `- ${concept}`).join('\n')}

USER REQUEST: ${userPrompt}

Please create a NEW design concept that:
1. Incorporates the user's request
2. Is meaningfully different from existing concepts
3. Is manufacturable and commercially viable
4. Maintains the core product functionality

Respond with JSON only:
{
  "concept_title": "<short title under 8 words>",
  "generated_image_prompt": "<detailed visual description for generating the concept image>",
  "short_description": "<under 20 words>",
  "design_rationale": "<why this design is compelling and different from existing concepts>"
}`;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: conceptPrompt
          }]
        }],
        generationConfig: fastMode ? {
          temperature: 0.5,
          maxOutputTokens: 1024,
        } : {
          temperature: 0.7,
          maxOutputTokens: 2048,
        },
      }),
    }
  );

  if (!response.ok) {
    throw new Error(`Gemini API error: ${response.statusText}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  
  if (!text) {
    throw new Error('No response from Gemini');
  }

  // Extract JSON from response
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error('No JSON found in Gemini response');
  }

  return JSON.parse(jsonMatch[0]);
}

export async function POST(request: NextRequest) {
  try {
    const { originalProduct, userPrompt, existingConcepts, fastMode = true } = await request.json();

    if (!originalProduct || !userPrompt) {
      return NextResponse.json(
        { error: 'Original product and user prompt are required' },
        { status: 400 }
      );
    }

    // Generate the concept details
    const conceptDetails = await callGeminiForConcept(originalProduct, userPrompt, existingConcepts, Boolean(fastMode));

    // Generate the image for the concept
    const imageUrl = await generateImageWithImagen(conceptDetails.generated_image_prompt, Boolean(fastMode));

    return NextResponse.json({
      success: true,
      ...conceptDetails,
      generated_image_url: imageUrl,
    });

  } catch (error) {
    console.error('Error generating concept:', error);
    
    return NextResponse.json(
      { 
        error: 'Failed to generate concept',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
